### ISSUE TITLE
Server crashes when loading certain maps

### ISSUE THREAD

**Issue by liekki** [alcachofass/rocketarena3container#1]
I was able to get my own sever up and running with this project, however when the timelimit hits and the server tries to load the map `ra3map2`, the server will segfault with the following entries on the log:

```
ra3_rocketArena3.1.mms4roa53kvs@| ------- BotLib Initialization -------
ra3_rocketArena3.1.mms4roa53kvs@| loaded weapons.c
ra3_rocketArena3.1.mms4roa53kvs@| loaded items.c
ra3_rocketArena3.1.mms4roa53kvs@| loaded syn.c
ra3_rocketArena3.1.mms4roa53kvs@| loaded rnd.c
ra3_rocketArena3.1.mms4roa53kvs@| loaded match.c
ra3_rocketArena3.1.mms4roa53kvs@| loaded rchat.c
ra3_rocketArena3.1.mms4roa53kvs@| ------------ Map Loading ------------
ra3_rocketArena3.1.mms4roa53kvs@    | trying to load maps/ra3map2.aas
ra3_rocketArena3.1.mms4roa53kvs@| ^1Fatal: can't open maps/ra3map2.aas
ra3_rocketArena3.1.mms4roa53kvs@    | 32 bots parsed
ra3_rocketArena3.1.mms4roa53kvs@| 35 arenas parsed
ra3_rocketArena3.1.mms4roa53kvs@| Map loop read
ra3_rocketArena3.1.mms4roa53kvs@| Default pickup mode is: clanarena
ra3_rocketArena3.1.mms4roa53kvs@| Received signal 11, exiting...
ra3_rocketArena3.1.mms4roa53kvs@| ----- Server Shutdown (Signal caught) -----
ra3_rocketArena3.1.mms4roa53kvs@| Sending heartbeat to master.ioquake3.org:27950
ra3_rocketArena3.1.mms4roa53kvs@| Sending heartbeat to master.ioquake3.org:27950
ra3_rocketArena3.1.mms4roa53kvs@| ==== ShutdownGame ====
ra3_rocketArena3.1.mms4roa53kvs@| Waiting on threads...
ra3_rocketArena3.1.mms4roa53kvs@| ********************
ra3_rocketArena3.1.mms4roa53kvs@| ERROR: Could not deinitialize mutexes!
ra3_rocketArena3.1.mms4roa53kvs@| ********************
ra3_rocketArena3.1.mms4roa53kvs@| ----- Server Shutdown (Server crashed: Could not deinitialize mutexes!) -----
ra3_rocketArena3.1.mms4roa53kvs@| Sending heartbeat to master.ioquake3.org:27950
ra3_rocketArena3.1.mms4roa53kvs@| Sending heartbeat to master.ioquake3.org:27950
ra3_rocketArena3.1.mms4roa53kvs@| ==== ShutdownGame ====
ra3_rocketArena3.1.mms4roa53kvs@| /usr/lib/ioquake3/arena/ra3server.sh: line 1:     7 Segmentation fault      (core dumped) /usr/lib/ioquake3/ra3ded +set vm_game 0 +set sv_pure 1 +set dedicated 2 +set net_port 27960 +set sv_master1 master.ioquake3.org:27950 +exec server.cfg
``` 

Some maps im able to load in, but some - like `ra3map2` and `ra3map3` for example just crash the server. Any ideas? Have you been able to run these maps without any problems.

**Comment by alcachofass** [comment]
Interesting. I do not believe I've seen that issue. However, I tend to use the same map on my local server. Out of curiosity, are your RA maps in the Arena folder or in BaseQ3 folder?

**Comment by liekki** [comment]
I have the maps in the `arena` folder. 

I can still try to see if i can get this ioquake+rocket arena 1.8 to work, but meanwhile I tried the approach as described in this [q3ra3 project](https://github.com/ra3se/q3ra3-server) which is based on quake3e and rocket arena 1.76 and it seems to be working. Seems like its an issue specific to ra180 + ioquake, maybe related to the architectures x86 vs x64

**Comment by alcachofass** [comment]
No worries. I appreciate the feedback. 
It is possible 1.8 is the issue since it introduced the dependency on the ra3ded binary. In practice, 1.76 was the most popular version of the mod. You can effectively run 1.76 with this container by changing the docker launch command at build time.
